// MYP-specific LLVM passes.
//
// These passes encode MYP *semantics* that the generic LLVM pipeline cannot
// see: codegen shapes (redundant double initialization stores) and runtime
// intrinsics (myp_alloc / memset-zero new-object pattern, etc.).
//
// Every pass follows the New Pass Manager contract: return
// PreservedAnalyses::none() if IR changed, ::all() otherwise.

#include "mylang/MypPasses.h"

#include <llvm/ADT/SmallVector.h>
#include <llvm/ADT/StringRef.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/Module.h>
#include <llvm/Passes/PassBuilder.h>
#include <llvm/Passes/PassPlugin.h>

namespace mylang {
namespace {

/// Is \p I a memory-observing or memory-mutating instruction? Used to decide
/// whether we may delete a store that precedes \p I without checking whether
/// \p I reads the stored location.
static bool isMemoryAccessing(const llvm::Instruction& I) {
    if (llvm::isa<llvm::LoadInst>(I) || llvm::isa<llvm::StoreInst>(I) ||
        llvm::isa<llvm::CallInst>(I) || llvm::isa<llvm::InvokeInst>(I) ||
        llvm::isa<llvm::FenceInst>(I) || llvm::isa<llvm::AtomicRMWInst>(I) ||
        llvm::isa<llvm::AtomicCmpXchgInst>(I))
        return true;
    return false;
}

/// MypRedundantStorePass
///
/// Removes *dead* stores generated by the MYP code generator, e.g. the double
/// initialization for `int x = 0;`:
///
///   store i32 0, ptr %x      <- dead (immediately overwritten, nothing reads)
///   store i32 0, ptr %x
///
/// Rule (conservative): within a single basic block, for two stores to the
/// *same pointer operand* where every instruction between them is
/// memory-neutral (no load/store/call/atomic/fence), the earlier store is
/// dead and can be erased. This is trivially safe: nothing between the two
/// stores can observe the first value.
struct MypRedundantStorePass : public llvm::PassInfoMixin<MypRedundantStorePass> {
    llvm::PreservedAnalyses run(llvm::Function& F,
                                llvm::FunctionAnalysisManager&) {
        bool changed = false;
        for (auto& BB : F) {
            // Collect all stores in this block in order.
            std::vector<llvm::StoreInst*> stores;
            for (auto& I : BB)
                if (auto* SI = llvm::dyn_cast<llvm::StoreInst>(&I))
                    stores.push_back(SI);

            std::vector<llvm::StoreInst*> toErase;
            for (size_t i = 0; i + 1 < stores.size(); ++i) {
                llvm::StoreInst* S1 = stores[i];
                llvm::StoreInst* S2 = stores[i + 1];
                if (S1->isVolatile() || S2->isVolatile()) continue;
                if (S1->getPointerOperand() != S2->getPointerOperand()) continue;

                // Everything strictly between S1 and S2 must be memory-neutral.
                bool clean = true;
                for (auto It = llvm::BasicBlock::iterator(S1),
                          End = llvm::BasicBlock::iterator(S2);
                     ++It != End;) {
                    if (isMemoryAccessing(*It)) { clean = false; break; }
                }
                if (clean) toErase.push_back(S1);
            }

            for (auto* SI : toErase) {
                SI->eraseFromParent();
                changed = true;
            }
        }
        return changed ? llvm::PreservedAnalyses::none()
                       : llvm::PreservedAnalyses::all();
    }
};

} // namespace

void registerMypPasses(llvm::PassBuilder& PB,
                       llvm::ModulePassManager& MPM,
                       llvm::OptimizationLevel OL) {
    // --- B) register "-passes=..." parsing callback (nested pipelines, e.g.
    //     "module(myp-pass)" when driven by `opt`/PassBuilder::parsePassPipeline).
    PB.registerPipelineParsingCallback(
        [](llvm::StringRef Name, llvm::ModulePassManager& Passes,
           llvm::ArrayRef<llvm::PassBuilder::PipelineElement>) {
            if (Name == "myp-pass") {
                Passes.addPass(
                    llvm::createModuleToFunctionPassAdaptor(MypRedundantStorePass()));
                return true;
            }
            return false;
        });

    // --- A) append MYP passes after the default -O pipeline ---
    if (OL != llvm::OptimizationLevel::O0) {
        MPM.addPass(
            llvm::createModuleToFunctionPassAdaptor(MypRedundantStorePass()));
    }
}

bool runMypPasses(llvm::Module& M, const std::string& passes) {
    llvm::LoopAnalysisManager LAM;
    llvm::FunctionAnalysisManager FAM;
    llvm::CGSCCAnalysisManager CGAM;
    llvm::ModuleAnalysisManager MAM;
    llvm::PassBuilder PB;
    PB.registerModuleAnalyses(MAM);
    PB.registerCGSCCAnalyses(CGAM);
    PB.registerFunctionAnalyses(FAM);
    PB.registerLoopAnalyses(LAM);
    PB.crossRegisterProxies(LAM, FAM, CGAM, MAM);

    llvm::ModulePassManager MPM;
    bool known = true;
    llvm::SmallVector<llvm::StringRef, 4> names;
    llvm::StringRef(passes).split(names, ',', -1, /*KeepEmpty=*/false);
    for (llvm::StringRef n : names) {
        llvm::StringRef name = n.trim();
        if (name == "myp-pass") {
            MPM.addPass(
                llvm::createModuleToFunctionPassAdaptor(MypRedundantStorePass()));
        } else {
            known = false;
        }
    }
    if (!known || names.empty()) return false;
    MPM.run(M, MAM);
    return true;
}

} // namespace mylang
