// MYP-specific LLVM passes.
//
// These passes encode MYP *semantics* that the generic LLVM pipeline cannot
// see: codegen shapes (redundant double initialization stores) and runtime
// intrinsics (myp_alloc / memset-zero new-object pattern, etc.).
//
// Every pass follows the New Pass Manager contract: return
// PreservedAnalyses::none() if IR changed, ::all() otherwise.

#include "mylang/MypPasses.h"

#include <llvm/ADT/SmallVector.h>
#include <llvm/ADT/StringRef.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/Module.h>
#include <llvm/Passes/PassBuilder.h>
#include <llvm/Passes/PassPlugin.h>

namespace mylang {
namespace {

/// Is \p I a memory-observing or memory-mutating instruction? Used to decide
/// whether we may delete a store that precedes \p I without checking whether
/// \p I reads the stored location.
static bool isMemoryAccessing(const llvm::Instruction& I) {
    if (llvm::isa<llvm::LoadInst>(I) || llvm::isa<llvm::StoreInst>(I) ||
        llvm::isa<llvm::CallInst>(I) || llvm::isa<llvm::InvokeInst>(I) ||
        llvm::isa<llvm::FenceInst>(I) || llvm::isa<llvm::AtomicRMWInst>(I) ||
        llvm::isa<llvm::AtomicCmpXchgInst>(I))
        return true;
    return false;
}

/// MypRedundantStorePass
///
/// Removes *dead* stores generated by the MYP code generator, e.g. the double
/// initialization for `int x = 0;`:
///
///   store i32 0, ptr %x      <- dead (immediately overwritten, nothing reads)
///   store i32 0, ptr %x
///
/// Rule (conservative): within a single basic block, for two stores to the
/// *same pointer operand* where every instruction between them is
/// memory-neutral (no load/store/call/atomic/fence), the earlier store is
/// dead and can be erased. This is trivially safe: nothing between the two
/// stores can observe the first value.
struct MypRedundantStorePass : public llvm::PassInfoMixin<MypRedundantStorePass> {
    llvm::PreservedAnalyses run(llvm::Function& F,
                                llvm::FunctionAnalysisManager&) {
        bool changed = false;
        for (auto& BB : F) {
            // Collect all stores in this block in order.
            std::vector<llvm::StoreInst*> stores;
            for (auto& I : BB)
                if (auto* SI = llvm::dyn_cast<llvm::StoreInst>(&I))
                    stores.push_back(SI);

            std::vector<llvm::StoreInst*> toErase;
            for (size_t i = 0; i + 1 < stores.size(); ++i) {
                llvm::StoreInst* S1 = stores[i];
                llvm::StoreInst* S2 = stores[i + 1];
                if (S1->isVolatile() || S2->isVolatile()) continue;
                if (S1->getPointerOperand() != S2->getPointerOperand()) continue;

                // Everything strictly between S1 and S2 must be memory-neutral.
                bool clean = true;
                for (auto It = llvm::BasicBlock::iterator(S1),
                          End = llvm::BasicBlock::iterator(S2);
                     ++It != End;) {
                    if (isMemoryAccessing(*It)) { clean = false; break; }
                }
                if (clean) toErase.push_back(S1);
            }

            for (auto* SI : toErase) {
                SI->eraseFromParent();
                changed = true;
            }
        }
        return changed ? llvm::PreservedAnalyses::none()
                       : llvm::PreservedAnalyses::all();
    }
};

static llvm::StringRef calledName(const llvm::CallBase& call) {
    if (auto* callee = call.getCalledFunction()) return callee->getName();
    return {};
}

/// Transfer the initial rc=1 of a fresh class object into one strong store:
///
///   %p = call @myp_alloc_object(...)
///   call @myp_retain(%p)
///   call @myp_release(%old)
///   store %p, %slot
///   call @myp_release(%p)
///
/// Fresh allocation makes `%old == %p` impossible, so the retain-before-release
/// self-assignment guard is unnecessary. Removing the matching pair leaves the
/// same final rc while transferring the allocation's initial ownership to slot.
/// Keep this deliberately local: one basic block, exactly one pointer store,
/// and no other use of the fresh value between the pair.
struct MypArcTransferPass : public llvm::PassInfoMixin<MypArcTransferPass> {
    llvm::PreservedAnalyses run(llvm::Function& function,
                                llvm::FunctionAnalysisManager&) {
        bool changed = false;
        for (auto& block : function) {
            llvm::SmallVector<std::pair<llvm::CallBase*, llvm::CallBase*>, 4> pairs;
            for (auto& instruction : block) {
                auto* retain = llvm::dyn_cast<llvm::CallBase>(&instruction);
                if (!retain || calledName(*retain) != "myp_retain" ||
                    retain->arg_size() != 1)
                    continue;

                llvm::Value* value = retain->getArgOperand(0)->stripPointerCasts();
                auto* allocation = llvm::dyn_cast<llvm::CallBase>(value);
                if (!allocation || calledName(*allocation) != "myp_alloc_object")
                    continue;

                llvm::StoreInst* ownershipStore = nullptr;
                llvm::CallBase* release = nullptr;
                bool invalid = false;
                for (auto iterator = std::next(llvm::BasicBlock::iterator(retain));
                     iterator != block.end(); ++iterator) {
                    llvm::Instruction& current = *iterator;
                    bool usesValue = false;
                    for (llvm::Use& operand : current.operands()) {
                        if (operand.get()->stripPointerCasts() == value) {
                            usesValue = true;
                            break;
                        }
                    }
                    if (!usesValue) continue;

                    if (auto* store = llvm::dyn_cast<llvm::StoreInst>(&current)) {
                        if (store->getValueOperand()->stripPointerCasts() == value &&
                            !ownershipStore) {
                            ownershipStore = store;
                            continue;
                        }
                    }
                    if (auto* call = llvm::dyn_cast<llvm::CallBase>(&current)) {
                        if (calledName(*call) == "myp_release" &&
                            call->arg_size() == 1 && call->use_empty() &&
                            call->getArgOperand(0)->stripPointerCasts() == value &&
                            ownershipStore) {
                            release = call;
                            break;
                        }
                    }
                    invalid = true;
                    break;
                }
                if (!invalid && ownershipStore && release)
                    pairs.push_back({retain, release});
            }
            for (auto [retain, release] : pairs) {
                retain->eraseFromParent();
                release->eraseFromParent();
                changed = true;
            }
        }
        return changed ? llvm::PreservedAnalyses::none()
                       : llvm::PreservedAnalyses::all();
    }
};

} // namespace

void registerMypPasses(llvm::PassBuilder& PB,
                       llvm::ModulePassManager& MPM,
                       llvm::OptimizationLevel OL) {
    // --- B) register "-passes=..." parsing callback (nested pipelines, e.g.
    //     "module(myp-pass)" when driven by `opt`/PassBuilder::parsePassPipeline).
    PB.registerPipelineParsingCallback(
        [](llvm::StringRef Name, llvm::ModulePassManager& Passes,
           llvm::ArrayRef<llvm::PassBuilder::PipelineElement>) {
            if (Name == "myp-pass") {
                Passes.addPass(
                    llvm::createModuleToFunctionPassAdaptor(MypRedundantStorePass()));
                Passes.addPass(
                    llvm::createModuleToFunctionPassAdaptor(MypArcTransferPass()));
                return true;
            }
            if (Name == "myp-arc-transfer") {
                Passes.addPass(
                    llvm::createModuleToFunctionPassAdaptor(MypArcTransferPass()));
                return true;
            }
            return false;
        });

    // --- A) append MYP passes after the default -O pipeline ---
    if (OL != llvm::OptimizationLevel::O0) {
        MPM.addPass(
            llvm::createModuleToFunctionPassAdaptor(MypRedundantStorePass()));
        MPM.addPass(
            llvm::createModuleToFunctionPassAdaptor(MypArcTransferPass()));
    }
}

bool runMypPasses(llvm::Module& M, const std::string& passes) {
    llvm::LoopAnalysisManager LAM;
    llvm::FunctionAnalysisManager FAM;
    llvm::CGSCCAnalysisManager CGAM;
    llvm::ModuleAnalysisManager MAM;
    llvm::PassBuilder PB;
    PB.registerModuleAnalyses(MAM);
    PB.registerCGSCCAnalyses(CGAM);
    PB.registerFunctionAnalyses(FAM);
    PB.registerLoopAnalyses(LAM);
    PB.crossRegisterProxies(LAM, FAM, CGAM, MAM);

    llvm::ModulePassManager MPM;
    bool known = true;
    llvm::SmallVector<llvm::StringRef, 4> names;
    llvm::StringRef(passes).split(names, ',', -1, /*KeepEmpty=*/false);
    for (llvm::StringRef n : names) {
        llvm::StringRef name = n.trim();
        if (name == "myp-pass") {
            MPM.addPass(
                llvm::createModuleToFunctionPassAdaptor(MypRedundantStorePass()));
            MPM.addPass(
                llvm::createModuleToFunctionPassAdaptor(MypArcTransferPass()));
        } else if (name == "myp-arc-transfer") {
            MPM.addPass(
                llvm::createModuleToFunctionPassAdaptor(MypArcTransferPass()));
        } else {
            known = false;
        }
    }
    if (!known || names.empty()) return false;
    MPM.run(M, MAM);
    return true;
}

} // namespace mylang
